- controller/auth/impl.go
- service/auth/impl.go
- service/auth/interface.go
- service/auth/provider/fake.go
- service/auth/provider/google.go
- service/auth/provider/interface.go
- template/redirect.html
- test/service/auth/auth_test.go
Closes #7 
This allows extensions to core to call into the login flow and specify a redirect back to their sites. The extensions will receive a code which they can exchange for an ACM@UIUC Core token by posting to the endpoint for their specified oauth provider. Once the extension has received the token from this exchange it can perform operations such as obtaining a user's username and verifying their group membership.
> Add extension interface

- Makefile
- gitstore/impl.go
- scripts/run-dev.sh
Handles part of #20 
When `IS_DEV=true` is set the gitstore uri will be treated as a file uri. A new makefile target (`make run-dev`)is added to simplify running Core in dev mode.
> Use local data in dev mode

- config/config.go
- controller/site/impl.go
- scripts/run-dev.sh
- service/auth/provider/fake.go
- service/auth/provider/interface.go
- template/login.html
Handles part of #20 
When `IS_DEV=true` is set, the login page will render an auth bypass button that automatically logs in the developer as the oauth fake user. The email for this user can be set with `OAUTH_FAKE_USER=<email>`.
Currently `make run-dev` will impersonate `arnavs3` for local development.
> Local auth bypass

- Makefile
Handles part of #20 
Adds `make dev-reset` which will connect to the mysql instance running on localhost and drop the current `core` database and then run all of the migrations to rebuild the schema.
Adds `make dev-run` which will start the `core` binary in dev mode.
> Add dev make targets

- README.md
- development.md
Handles part of #20 
Adds documentation about how to setup a development environment and how to use the provided `make dev-*` targets.
> Add Dev Docs

- context/context.go
- controller/controller.go
- middleware/authorization.go
Closes #19 
Adds logic to render the generated authentication error into the correct format depending on if the error occurs on an api endpoint or a web page endpoint.
> Improve auth errors

- controller/resume/impl.go
- controller/site/impl.go
- controller/user/impl.go
- database/migration/add_resumes_timestamp.go
- database/migration/add_users_timestamp.go
- database/migration/migrations.go
- model/resume.go
- model/user.go
- service/resume/impl.go
- service/user/impl.go
- template/resumemanager.html
- template/usermanager.html
- test/service/resume/resume_test.go
- test/service/user/user_test.go
Closes #16 
Closes #17 
Adds `created_at` timestamp to the user data and adds a `updated_at` timestamp to the resume data. These timestamps are injected in the `CreateUser` and `UploadResume` endpoints. These timestamps are displayed in the user manager and the resume manager.
> Add timestamps to users and resumes table

- extensions.md
Closes #30 
This PR adds a simple example extension to the `extensions.md` documentation file. The sample extension acts as a `whoami` application which allows user to login and get back their user information rendered as a json string in the browser.
> Add extension documentation

- template/home.html
The message on the home page is rather long can cause the line to wrap. This change reverts the message to the original 'Welcome!' that was in the prior version of the website.
> Shorten home page terminal message

- config/config.go
- controller/controller.go
- controller/site/impl.go
- data/intranet.yaml
- model/group.go
- model/intranet.go
- template/intranet.html
The data for the intranet page is now generated from the data file at `data/intranet.yaml`. Access to cards can be controlled by either user mark or group membership. A user will be granted access to a card if they can match either mark or a group membership.
Access to the intranet page is now also available to all logged in members. However cards will be displayed selectively based on mark and group membership.
> Template Intranet Page

- controller/controller.go
- controller/site/impl.go
- service/user/impl.go
- template/join.html
- template/login.html
This PR makes the following changes to the login workflow:
- Successful logins are redirected to `/intranet`
- If a user has not filled out the join form `/intranet` renders the join form
- Filling out the join form redirects to `/intranet`
> Improved login workflows

- controller/site/impl.go
This PR further improves the redirects which occur during first-time login and signup. Hitting `/intranet` will now first check for if the user is logged-in. If not then the user is redirected to the login page. If the user is logged-in, but has not filled our the join form then they are redirected to the join form. Filling out the join form / logging in will still redirect to `/intranet`.
> Improve login and signup redirects

- development.md
This PR adds documentation about what user is being impersonated in development mode.
> Add note about dev mode user

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- cloudbuild.yaml
- data/groups.yaml
- data/hackillinois.yaml
- data/reflectionsprojections.yaml
- test/data/groups.yaml
- test/service/group/group_test.go
This PR adds a linting workflow to github actions. This will ensure that all code and data committed to this repository is properly formatted.
> Add linting workflow

- service/resume/impl.go
- service/user/impl.go
Loading the resume book is currently much slower than loading the user manager page even though there is much more data in the user manager page. The reason for this is likely the serial signing of URIs for the resumes.
This PR parallelizes that signing process over eight worker routines in order to reduce that overhead.
> Parallel resume uri signing

- data/groups.yaml
Fix the description for SIGArch.
> Spelling fix

- data/groups.yaml
> Fix yaml failures

- data/groups.yaml
Mainly doing this to verify the automated build & deploy works on the new repo...
> Add cding20 to admin

- controller/site/impl.go
- template/join.html
We already have logic in place to redirect authenticated user that do not have an account to the `/join` page. This PR adds a message to that page explaining what the user should do. This message is primarily targeted at recruiters which might login to the page before their account is created and be confused by the join form (which is only for UIUC members).
> Add message when authenticated, but account doesn't exist

- data/groups.yaml
This PR updates some SIG leaders based on the transition which we know will happen going into Fall 2020.
> Update SIG leaders

- config/config.go
The gitstore uri was not updated when the repository was migrated to https://github.com/acm-uiuc/core.
> Update gitstore base uri

- data/about.yaml
- model/about.go
- template/about.html
Fixes typo: `facilites` => `facilities`
> Fix facilities typo

- data/groups.yaml
Meeting zoom link and meeting time will be determined within the next week or so.
> Add SIGHPC group info to SIGs page.

- data/groups.yaml
- model/group.go
- template/sigs.html
- test/data/groups.yaml
Close #28 
You can add multiple meeting times for a SIG in `groups.yaml` in the format:
```
meetings:
- topic: General Meeting
meetingTime: 'Thursday 5:00 PM - 6:00 PM'
meetingLocation: Siebel 1109
```
They will then show up on the `sigs.html` page.
> Add the ability to support multiple meeting times for SIGs (#28)

- template/header.html
- template/history.html
Fixed the [history page](https://acm.illinois.edu/about/history)'s footer so it is no longer squished.
Before:
After:
> fix history page footer

- data/groups.yaml
- data/hackillinois.yaml
- data/reflectionsprojections.yaml
> Revert "updated data in about us, sig, r|p"
